### ISSUE TITLE
TPPFLUSH floods console whenever server.send() is called

### ISSUE THREAD

**Issue by MissingNO123** [hlixed/TPPFLUSH#4]
Every time `server.send()` is called (which is frequently) it also prints the bytearray `toSend`, which floods the console and makes anything unreadable. The print function should be removed (or made optional if possible).

(also, a more optimal way to print the bytearray would be `print(''.join(format(x, '02x') for x in toSend))`)

**Comment by hlixed** [comment]
I already made it optional a while ago in anticipation of this very issue; the boolean print_sent argument, if set to False, hides the printing.

try `server.send(print_sent=False)`.

**Comment by hlixed** [comment]
Also, I should mention, that feature was added as of commit ccf3eedb56b0a161fc1bab992803b24936b6df1e, so you should be set to use the argument if you update your submodule.
